name: Working with GitHub Pages
markdown: redcarpet
pygments: true
authors:
  Ramona:
    name: Lindsey Fox
    display_name: Lindsey 
    email: lindsey.c.langsdon@vanderbilt.edu
    twitter: lclfox
    github: langsdlc
