name: Working with GitHub Pages
markdown: redcarpet
pygments: true
authors:
  Ramona:
    name: Ramona Romero
    display_name: Ramona
    email: ramona.romero@vanderbilt.edu
    twitter: Ramona2020
    github: Ramona2020
